<?php $_product = $this->getProduct(); ?>
<?php $buttonTitle = $this->__('kostenlos anfragen'); ?>
<?php if($_product->isSaleable()): ?>
    <div class="add-to-cart">

        <button type="button" title="<?php echo $buttonTitle ?>" class="button btn-cart" onclick="productAddToCartForm.submit(this)"><span><span><i class="icon-mail-alt"></i><?php echo $buttonTitle ?></span></span></button>
        <?php echo $this->getChildHtml('', true, true) ?>
    </div>
<?php endif; ?>
